# This file was generated by GoReleaser. DO NOT EDIT.
cask "huecli" do
  name "huecli"
  desc ""
  homepage "https://github.com/MoAlshatti/hue-bridge-TUI"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "huecli"

  on_macos do
    url "https://github.com/MoAlshatti/hue-bridge-TUI/releases/download/v#{version}/huecli_#{version}_darwin_all.tar.gz"
    sha256 "a147da76ad9891a76abcc7551e386a94b463931bc67c39de436d0ae89af398d6"
  end

  on_linux do
    on_intel do
      url "https://github.com/MoAlshatti/hue-bridge-TUI/releases/download/v#{version}/huecli_#{version}_linux_amd64.tar.gz"
      sha256 "ff41c31160bad0e06a0ba8da6e601949c6b209b6ae4c5f361f4290d226f9c105"
    end
    on_arm do
      url "https://github.com/MoAlshatti/hue-bridge-TUI/releases/download/v#{version}/huecli_#{version}_linux_arm64.tar.gz"
      sha256 "08c806710e002137a3b18ed3bea30d9786b4267cfc24c634daa5e6bc403c2952"
    end
  end

  # No zap stanza required
end
