# This file was generated by GoReleaser. DO NOT EDIT.
cask "huecli" do
  desc ""
  homepage "https://github.com/MoAlshatti/hue-bridge-TUI"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "huecli"

  on_macos do
    url "https://github.com/MoAlshatti/hue-bridge-TUI/releases/download/v0.1.0/huecli_0.1.0_darwin_all.tar.gz"
    sha256 "0ac2d80ecfabeb15da51912815db11792c077a977821403cda95f824ca016a2e"
  end

  on_linux do
    on_intel do
      url "https://github.com/MoAlshatti/hue-bridge-TUI/releases/download/v0.1.0/huecli_0.1.0_linux_amd64.tar.gz"
      sha256 "a67ab9aeed2be64283d3a4742476e91504ac57134a37bbd777db33cec2373f71"
    end
    on_arm do
      url "https://github.com/MoAlshatti/hue-bridge-TUI/releases/download/v0.1.0/huecli_0.1.0_linux_arm64.tar.gz"
      sha256 "7608d2699b6684273d0df8e984c7620f964f8163f2795d31b4bbeadfa02c8e64"
    end
  end

  # No zap stanza required
end
