# This file was generated by GoReleaser. DO NOT EDIT.
cask "huecli" do
  desc ""
  homepage "https://github.com/MoAlshatti/hue-bridge-TUI"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "huecli"

  on_macos do
    url "https://github.com/MoAlshatti/hue-bridge-TUI/releases/download/v0.1.1/huecli_0.1.1_darwin_all.tar.gz"
    sha256 "f7f24cb789687a330e64b0664953e9e06f676be0a366588ed8b5a52ed6a1c9b7"
  end

  on_linux do
    on_intel do
      url "https://github.com/MoAlshatti/hue-bridge-TUI/releases/download/v0.1.1/huecli_0.1.1_linux_amd64.tar.gz"
      sha256 "6ee0fad823b0fc4e29fe8a773ad4c6d2571fb1e60db031001a15316709c2e509"
    end
    on_arm do
      url "https://github.com/MoAlshatti/hue-bridge-TUI/releases/download/v0.1.1/huecli_0.1.1_linux_arm64.tar.gz"
      sha256 "4b83d4e45124bf857541ae9d5518db6512ba620e3c54943181be0bcc6a951bc0"
    end
  end

  # No zap stanza required
end
